### ISSUE TITLE
Bug: Infinite source block deletion

### ISSUE THREAD

**Issue by Zentheon** [codewarrior0/sips#2]
Even after a L'il Sip or jug is already full with any liquid, you can still endlessly right-click pick up any source block (though it doesn't go anywhere once it's full). Basically acts as a creative mode bucket.

**Comment by Yoghurt4C** [comment]
fixed in https://github.com/codewarrior0/sips/commit/4cd50ccc662377b27aafc37380a54be6b2659be0 unless you didn't want that, in which case: too bad!
